# Generated by Django 4.2.11 on 2024-03-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0004_alter_box_creator_alter_box_last_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
