# Generated by Django 2.0.9 on 2019-04-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Text to display in the banner's button",
                        max_length=1024,
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        help_text="Message to display in the banner", max_length=2048
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        help_text="Link the button will go to", max_length=1024
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=False, help_text="Make the banner active on the site"
                    ),
                ),
                (
                    "psf_pages_only",
                    models.BooleanField(
                        default=True, help_text="Display the banner on /psf pages only"
                    ),
                ),
            ],
        )
    ]
