# Generated by Django 2.0.9 on 2019-04-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('message', models.CharField(max_length=2048)),
                ('link', models.CharField(max_length=1024)),
                ('active', models.BooleanField(default=False)),
                ('psf_pages_only', models.BooleanField(default=True)),
            ],
        ),
    ]
