# Generated by Django 2.0.9 on 2019-04-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='active',
            field=models.BooleanField(default=False, help_text='Make the banner active on the site'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.CharField(help_text='Link the button will go to', max_length=1024),
        ),
        migrations.AlterField(
            model_name='banner',
            name='message',
            field=models.CharField(help_text='Message to display in the banner', max_length=2048),
        ),
        migrations.AlterField(
            model_name='banner',
            name='psf_pages_only',
            field=models.BooleanField(default=True, help_text='Display the banner on /psf pages only'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(help_text="Text to display in the banner's button", max_length=1024),
        ),
    ]
