# Generated by Django 2.0.13 on 2020-10-09 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('minutes', '0002_auto_20150416_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('parent_concern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_concerns', to='minutes.Concern')),
            ],
            options={
                'verbose_name': 'concern',
                'verbose_name_plural': 'concerns',
            },
        ),
        migrations.CreateModel(
            name='ConcernedParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'concerned party',
                'verbose_name_plural': 'concerned parties',
            },
        ),
        migrations.CreateModel(
            name='ConcernRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('concern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minutes.Concern')),
            ],
            options={
                'verbose_name': 'concern role',
                'verbose_name_plural': 'concern roles',
            },
        ),
        migrations.AddField(
            model_name='concernedparty',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minutes.ConcernRole'),
        ),
        migrations.AddField(
            model_name='concernedparty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
