# Generated by Django 2.0.13 on 2020-10-14 14:21

from django.db import migrations, models
import django.db.models.deletion
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0004_auto_20201009_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinuteItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('content', markupfield.fields.MarkupField(rendered_field=True)),
                ('content_markup_type', models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown'), ('restructuredtext', 'Restructured Text')], default='restructuredtext', max_length=30)),
                ('_content_rendered', models.TextField(editable=False)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minutes.Meeting')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
