# Generated by Django 2.0.13 on 2020-10-14 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0005_minuteitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitem',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='minutes.Meeting'),
        ),
        migrations.AlterField(
            model_name='minuteitem',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minute_items', to='minutes.Meeting'),
        ),
    ]
