# Generated by Django 2.0.13 on 2020-10-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0006_auto_20201014_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='ad_hoc_parties',
            field=models.ManyToManyField(blank=True, related_name='ad_hoc_meeting', to='minutes.ConcernedParty'),
        ),
    ]
