# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20170902_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('url', models.URLField(verbose_name='URL')),
                ('url_type', models.CharField(choices=[('meetup', 'meetup'), ('distribution list', 'distribution list'), ('other', 'other')], max_length=20)),
                ('start_date', models.DateField(null=True)),
                ('approved', models.BooleanField(default=False)),
                ('trusted', models.BooleanField(default=False)),
            ],
        ),
    ]
