# Generated by Django 4.2.17 on 2025-01-21 22:56

# Data migration: Merge MANAGING (3) membership_type into CONTRIBUTING (4)

from django.db import migrations


def update_membership_level(apps, schema_editor):
    Membership = apps.get_model('users', 'Membership')
    Membership.objects.filter(membership_type=3).update(membership_type=4)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_first_name'),
    ]

    operations = [
        migrations.RunPython(
            update_membership_level,
            migrations.RunPython.noop
        )
    ]
