# Generated by Django 4.2.16 on 2024-09-19 22:32

from django.db import migrations
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('successstories', '0012_alter_story_creator_alter_story_last_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=markupfield.fields.MarkupField(help_text='Note: Submissions in Markdown are strongly preferred and can be processed faster.', rendered_field=True),
        ),
    ]
