# Generated by Django 2.0.13 on 2020-10-28 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sponsors", "0007_auto_20201021_1410"),
    ]

    operations = [
        migrations.CreateModel(
            name="SponsorBenefit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="For display in the statement of work and sponsor dashboard.",
                        max_length=1024,
                        verbose_name="Benefit Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="For display in the statement of work and sponsor dashboard.",
                        null=True,
                        verbose_name="Benefit Description",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        help_text="Which sponsorship program the benefit is associated with.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sponsors.SponsorshipProgram",
                        verbose_name="Sponsorship Program",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SponsorContact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary",
                    models.BooleanField(
                        default=False,
                        help_text="If this is the primary contact for the sponsor",
                    ),
                ),
                (
                    "manager",
                    models.BooleanField(
                        default=False,
                        help_text="If this contact can manage sponsorship information on python.org",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=256)),
                (
                    "phone",
                    models.CharField(max_length=32, verbose_name="Contact Phone"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SponsorInformation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the sponsor, for public display.",
                        max_length=100,
                        verbose_name="Sponsor name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Brief description of the sponsor for public display.",
                        verbose_name="Sponsor description",
                    ),
                ),
                (
                    "landing_page_url",
                    models.URLField(
                        blank=True,
                        help_text="Sponsor landing page URL. This may be provided by the sponsor, however the linked page may not contain any sales or marketing information.",
                        null=True,
                        verbose_name="Sponsor landing page",
                    ),
                ),
                (
                    "web_logo",
                    models.ImageField(
                        help_text="For display on our sponsor webpage. High resolution PNG or JPG, smallest dimension no less than 256px",
                        upload_to="sponsor_web_logos",
                        verbose_name="Sponsor web logo",
                    ),
                ),
                (
                    "print_logo",
                    models.FileField(
                        blank=True,
                        help_text="For printed materials, signage, and projection. SVG or EPS",
                        null=True,
                        upload_to="sponsor_print_logos",
                        verbose_name="Sponsor print logo",
                    ),
                ),
                (
                    "primary_phone",
                    models.CharField(
                        max_length=32, verbose_name="Sponsor Primary Phone"
                    ),
                ),
                (
                    "mailing_address",
                    models.TextField(verbose_name="Sponsor Mailing/Billing Address"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sponsorship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applied_on", models.DateField(auto_now_add=True)),
                ("approved_on", models.DateField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("level_name", models.CharField(max_length=64)),
                ("sponsorship_fee", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "sponsor_info",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sponsors.SponsorInformation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sponsorcontact",
            name="sponsor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="sponsors.SponsorInformation",
            ),
        ),
        migrations.AddField(
            model_name="sponsorcontact",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sponsorbenefit",
            name="sponsorship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="benefits",
                to="sponsors.Sponsorship",
            ),
        ),
        migrations.AddField(
            model_name="sponsorbenefit",
            name="sponsorship_benefit",
            field=models.ForeignKey(
                help_text="Sponsorship Benefit this Sponsor Benefit came from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sponsors.SponsorshipBenefit",
            ),
        ),
    ]
