# Generated by Django 2.0.13 on 2020-11-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0010_auto_20201103_1313"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorship",
            name="finalized_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sponsorship",
            name="rejected_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sponsorship",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("rejected", "Rejected"),
                    ("approved", "Approved"),
                    ("finalized", "Finalized"),
                ],
                db_index=True,
                default="applied",
                max_length=20,
            ),
        ),
    ]
