# Generated by Django 2.0.13 on 2020-11-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0016_auto_20201119_1448"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorbenefit",
            name="added_by_user",
            field=models.BooleanField(default=False, verbose_name="Added by user?"),
        ),
    ]
