# Generated by Django 2.0.13 on 2020-12-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0017_sponsorbenefit_added_by_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalClause",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "internal_name",
                    models.CharField(
                        help_text="Friendly name used internally by PSF to reference this clause",
                        max_length=1024,
                        verbose_name="Internal Name",
                    ),
                ),
                (
                    "clause",
                    models.TextField(
                        help_text="Legal clause text to be added to statement of work",
                        verbose_name="Clause",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="PSF staff notes",
                        verbose_name="Notes",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="sponsorshipbenefit",
            name="package_only",
            field=models.BooleanField(
                default=False,
                help_text="If a benefit is only available via a sponsorship package, select this option.",
                verbose_name="Sponsor Package Only Benefit",
            ),
        ),
        migrations.AddField(
            model_name="sponsorshipbenefit",
            name="legal_clauses",
            field=models.ManyToManyField(
                blank=True,
                help_text="Legal clauses to be displayed in the statement of work",
                related_name="benefits",
                to="sponsors.LegalClause",
                verbose_name="Legal Clauses",
            ),
        ),
    ]
