# Generated by Django 2.0.13 on 2020-12-04 18:02

from django.db import migrations, models
import django.db.models.deletion
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0019_sponsor_twitter_handle"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatementOfWork",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("outdated", "Outdated"),
                            ("approved review", "Approved by reviewer"),
                            ("awaiting signature", "Awaiting signature"),
                            ("executed", "Executed"),
                            ("nullified", "Nullified"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "revision",
                    models.PositiveIntegerField(default=0, verbose_name="Revision nº"),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        upload_to="sponsors/statements_of_work/",
                        verbose_name="Unsigned PDF",
                    ),
                ),
                (
                    "signed_document",
                    models.FileField(
                        blank=True,
                        upload_to="sponsors/statmentes_of_work/signed/",
                        verbose_name="Signed PDF",
                    ),
                ),
                ("sponsor_info", models.TextField(verbose_name="Sponsor information")),
                ("sponsor_contact", models.TextField(verbose_name="Sponsor contact")),
                ("benefits_list", markupfield.fields.MarkupField(rendered_field=True)),
                (
                    "benefits_list_markup_type",
                    models.CharField(
                        choices=[
                            ("", "--"),
                            ("html", "HTML"),
                            ("plain", "Plain"),
                            ("markdown", "Markdown"),
                            ("restructuredtext", "Restructured Text"),
                        ],
                        default="markdown",
                        editable=False,
                        max_length=30,
                    ),
                ),
                ("legal_clauses", markupfield.fields.MarkupField(rendered_field=True)),
                ("_benefits_list_rendered", models.TextField(editable=False)),
                (
                    "legal_clauses_markup_type",
                    models.CharField(
                        choices=[
                            ("", "--"),
                            ("html", "HTML"),
                            ("plain", "Plain"),
                            ("markdown", "Markdown"),
                            ("restructuredtext", "Restructured Text"),
                        ],
                        default="markdown",
                        editable=False,
                        max_length=30,
                    ),
                ),
                ("created_on", models.DateField(auto_now_add=True)),
                ("_legal_clauses_rendered", models.TextField(editable=False)),
                ("last_update", models.DateField(auto_now=True)),
                ("sent_on", models.DateField(null=True)),
                (
                    "sponsorship",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="statement_of_work",
                        to="sponsors.Sponsorship",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statement of Work",
                "verbose_name_plural": "Statements of Work",
            },
        ),
    ]
