# Generated by Django 2.0.13 on 2020-12-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0019_statementofwork"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sponsorbenefit",
            options={"ordering": ("order",)},
        ),
        migrations.AddField(
            model_name="sponsorbenefit",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
    ]
