# Generated by Django 2.0.13 on 2021-02-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0019_sponsor_twitter_handle"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorshipbenefit",
            name="unavailable",
            field=models.BooleanField(
                default=False,
                help_text="If selected, this benefit will not be available to applicants.",
                verbose_name="Benefit is unavailable",
            ),
        ),
    ]
