# Generated by Django 2.0.13 on 2020-12-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0021_auto_20201211_2120"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorcontact",
            name="administrative",
            field=models.BooleanField(
                default=False,
                help_text="If this is an administrative contact for the sponsor",
            ),
        ),
    ]
