# Generated by Django 2.0.13 on 2021-04-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0022_sponsorcontact_administrative'),
        ('sponsors', '0020_sponsorshipbenefit_unavailable'),
    ]

    operations = [
    ]
