# Generated by Django 2.0.13 on 2021-04-16 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0024_auto_20210414_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Contract', 'verbose_name_plural': 'Contracts'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='sponsorship',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract', to='sponsors.Sponsorship'),
        ),
        migrations.AlterField(
            model_name='legalclause',
            name='clause',
            field=models.TextField(help_text='Legal clause text to be added to contract', verbose_name='Clause'),
        ),
        migrations.AlterField(
            model_name='sponsorbenefit',
            name='description',
            field=models.TextField(blank=True, help_text='For display in the contract and sponsor dashboard.', null=True, verbose_name='Benefit Description'),
        ),
        migrations.AlterField(
            model_name='sponsorbenefit',
            name='name',
            field=models.CharField(help_text='For display in the contract and sponsor dashboard.', max_length=1024, verbose_name='Benefit Name'),
        ),
        migrations.AlterField(
            model_name='sponsorshipbenefit',
            name='legal_clauses',
            field=models.ManyToManyField(blank=True, help_text='Legal clauses to be displayed in the contract', related_name='benefits', to='sponsors.LegalClause', verbose_name='Legal Clauses'),
        ),
        migrations.AlterField(
            model_name='sponsorshipbenefit',
            name='name',
            field=models.CharField(help_text='For display in the application form, contract, and sponsor dashboard.', max_length=1024, verbose_name='Benefit Name'),
        ),
    ]
