# Generated by Django 2.0.13 on 2021-08-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0033_tieredquantity_tieredquantityconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='document_docx',
            field=models.FileField(blank=True, upload_to='sponsors/statmentes_of_work/docx/', verbose_name='Unsigned Docx'),
        ),
    ]
