# Generated by Django 2.0.13 on 2021-08-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0041_auto_20210827_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorshippackage',
            name='logo_dimension',
            field=models.PositiveIntegerField(blank=True, default=175, help_text='Internal value used to control logos dimensions at sponsors page'),
        ),
    ]
