# Generated by Django 2.0.13 on 2021-08-27 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0042_auto_20210827_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsorship',
            old_name='level_name',
            new_name='level_name_old',
        ),
    ]
