# Generated by Django 2.2.24 on 2021-10-26 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0056_textasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericasset',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
