# Generated by Django 2.2.24 on 2021-12-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0065_auto_20211223_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorshippackage',
            name='slug',
            field=models.SlugField(help_text='Internal identifier used to reference this package.'),
        ),
    ]
