# Generated by Django 2.2.24 on 2021-12-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0066_auto_20211223_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorbenefit',
            name='a_la_carte',
            field=models.BooleanField(blank=True, default=False, verbose_name='Added as a la carte benefit?'),
        ),
    ]
