# Generated by Django 2.2.24 on 2022-07-28 16:04

from django.db import migrations


def populate_singleton(apps, schema_editor):
    SponsorshipCurrentYear = apps.get_model("sponsors.SponsorshipCurrentYear")
    SponsorshipCurrentYear.objects.get_or_create(id=1, defaults={"year": 2022})


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0077_sponsorshipcurrentyear'),
    ]

    operations = [
        migrations.RunPython(populate_singleton, migrations.RunPython.noop)
    ]
