# Generated by Django 2.2.24 on 2022-07-29 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0080_auto_20220728_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='application_year',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=2022, message='The min year value is 2022.'), django.core.validators.MaxValueValidator(limit_value=2050, message='The max year value is 2050.')]),
        ),
    ]
