# Generated by Django 2.2.24 on 2023-12-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0096_auto_20231214_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='renewal',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
