# Generated by Django 2.2.24 on 2023-12-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0097_sponsorship_renewal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='renewal',
            field=models.BooleanField(blank=True, help_text='If true, it means the sponsorship is a renewal of a previous sponsorship and will use the renewal template for contracting.', null=True),
        ),
    ]
