# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('jobs', '0016_auto_20170821_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.City'),
        ),
    ]
