# Generated by Django 2.0.6 on 2018-07-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_auto_20180705_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
