# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 01:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_auto_20170915_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_country',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_region',
        ),
    ]
