# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_auto_20170915_0118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_city',
            new_name='location',
        ),
    ]
