version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  groups:
    pip:
      patterns:
        - "*"
      # Review major upgrades separately.
      update-types:
        - minor
        - patch
  schedule:
    interval: quarterly
  cooldown:
    default-days: 7
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  groups:
    github-actions:
      patterns:
        - "*"  # Group all Actions updates into a single larger pull request
  schedule:
    interval: quarterly
  cooldown:
    default-days: 7
- package-ecosystem: docker
  directory: "/"
  groups:
    docker:
      patterns:
        - "*"
      # Review major upgrades separately.
      update-types:
        - minor
        - patch
  schedule:
    interval: quarterly
  cooldown:
    default-days: 7
