# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
# Project page: https://readthedocs.org/projects/pythondotorg/

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"

  commands:
      - python -m pip install -r docs-requirements.txt
      - make -C docs html JOBS=$(nproc) BUILDDIR=_readthedocs
      - mv docs/_readthedocs _readthedocs
