#!/usr/bin/env python3
"""
Bootstrap script for locating all dependencies on Windows.

check/locate Python 3
install/download virtualenv wheel if it is not installed

python -m virtualenv .locally
write description > .locally/README.md
.locally\Scripts\pip install -r dev-requirements.txt 

"""

# --- imports ---

import platform
import sys

# --- constants ---

PY3K = sys.version_info >= (3, 0)
ISWIN = platform.system() == 'Windows'
VDIR = '.virtenv/'

# --- helpers ---

# --[inline shellrun 2.0 import run]
import subprocess

class Result(object):
    def __init__(self, command=None, retcode=None, output=None):
        self.command = command or ''
        self.retcode = retcode
        self.output = output
        self.success = False
        if retcode == 0:
            self.success = True

def run(command):
    process = subprocess.Popen(command, shell=True)
    process.communicate()
    return Result(command=command, retcode=process.returncode)
# --[/inline]

if PY3K:
    interpreter = sys.executable
else:
    # [ ] try to detect Python 3
    sys.exit('This project only works with Python 3.')

print('--- creating virtualenv in .virtenv/ subdir ---')
if not run(interpreter + " -m virtualenv .virtenv").success:
    sys.exit('Error running virtualenv')

if ISWIN:
    interpreter = '.virtenv\\Scripts\\python.exe'
else:
    interpreter = '.virtenv/bin/python'
    

print('--- installing requirements ---')

if not run(interpreter + ' -m pip install -r requirements.txt').success:
    sys.exit('Error installing requirements.txt')


print('--- writing manage.bat file ---')
batfile = """\
@rem Autogenerated by bootstrap.py script.

@echo off
"{python}" manage.py %*
""".format(
  python=interpreter,
)
open('manage.bat', 'w').write(batfile)
