# Generated by Django 5.2.16 on 2026-09-30 16:46

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agreement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("kind", models.CharField(db_index=True, max_length=32)),
                ("title", models.CharField(max_length=255)),
                ("counterparty_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("offered", "Awaiting signature"),
                            ("signed", "Awaiting countersignature"),
                            ("executed", "Executed"),
                            ("declined", "Declined"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="offered",
                        max_length=16,
                    ),
                ),
                ("document_markdown", models.TextField()),
                ("document_sha256", models.CharField(max_length=64)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("offered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "signature_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("account", "Signed on python.org"),
                            ("link", "Signed on python.org with an emailed link"),
                            ("offline", "Signed copy on file"),
                        ],
                        max_length=16,
                    ),
                ),
                ("signer_name", models.CharField(blank=True, max_length=255)),
                ("signer_title", models.CharField(blank=True, max_length=255)),
                ("signer_email", models.EmailField(blank=True, max_length=254)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("signed_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("signed_user_agent", models.CharField(blank=True, max_length=512)),
                ("countersigner_name", models.CharField(blank=True, max_length=255)),
                ("countersigner_title", models.CharField(blank=True, max_length=255)),
                ("countersigned_at", models.DateTimeField(blank=True, null=True)),
                ("declined_at", models.DateTimeField(blank=True, null=True)),
                ("decline_reason", models.TextField(blank=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "counterparty_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="The python.org account that may view and sign it online.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agreements_to_sign",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "countersigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "declined_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "signature_recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "withdrawn_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-offered_at",),
                "permissions": (("manage_agreement", "Can prepare, edit, send, and countersign agreements"),),
            },
        ),
        migrations.CreateModel(
            name="SigningLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("token_sha256", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signing_links",
                        to="agreements.agreement",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Terms",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "under_review",
                    models.BooleanField(
                        default=False, help_text="Mark the terms as a draft for attorney review wherever they appear."
                    ),
                ),
                ("draft_markdown", models.TextField(blank=True, help_text="Working copy; not public until published.")),
                ("draft_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "draft_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "terms",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="CustomContract",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("counterparty_name", models.CharField(max_length=255, verbose_name="counterparty's legal name")),
                ("body_markdown", models.TextField(verbose_name="contract text")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "agreement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="custom_contract",
                        to="agreements.agreement",
                    ),
                ),
                (
                    "counterparty_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "terms",
                    models.ForeignKey(
                        blank=True,
                        help_text="Standing terms this contract cites and incorporates, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="agreements.terms",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="TermsVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.SlugField(max_length=64)),
                ("markdown", models.TextField()),
                ("sha256", models.CharField(editable=False, max_length=64)),
                ("notes", models.TextField(blank=True, help_text="What changed from the previous version.")),
                ("published_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "terms",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="versions", to="agreements.terms"
                    ),
                ),
            ],
            options={
                "ordering": ("-published_at", "-pk"),
            },
        ),
        migrations.AddField(
            model_name="agreement",
            name="terms_versions",
            field=models.ManyToManyField(blank=True, related_name="agreements", to="agreements.termsversion"),
        ),
        migrations.CreateModel(
            name="AgreementRevision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("revision", models.PositiveIntegerField()),
                ("markdown", models.TextField()),
                ("sha256", models.CharField(max_length=64)),
                ("note", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="revisions", to="agreements.agreement"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ("-revision",),
                "constraints": [models.UniqueConstraint(fields=("agreement", "revision"), name="one_row_per_revision")],
            },
        ),
        migrations.CreateModel(
            name="SignedCopy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[("customer", "Signed by the counterparty"), ("executed", "Signed by both parties")],
                        max_length=16,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("content", models.BinaryField()),
                ("sha256", models.CharField(max_length=64)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signed_copies",
                        to="agreements.agreement",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "signed copies",
                "constraints": [
                    models.UniqueConstraint(fields=("agreement", "kind"), name="one_signed_copy_of_each_kind")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="termsversion",
            constraint=models.UniqueConstraint(fields=("terms", "version"), name="one_terms_version_per_label"),
        ),
    ]
