# Generated by Django 5.2.16 on 2026-09-30 23:29

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.agreements.orders.catalog


class Migration(migrations.Migration):
    dependencies = [
        ("agreements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Allow anyone to browse this program and signed-in customers to start orders. Does not publish its terms. Leave unchecked for staff-prepared orders only.",
                    ),
                ),
                (
                    "definition",
                    models.JSONField(
                        help_text="Catalog, pricing rules and document copy.",
                        validators=[apps.agreements.orders.catalog.validate_catalog],
                    ),
                ),
            ],
            options={
                "ordering": ("title",),
            },
        ),
        migrations.AddField(
            model_name="terms",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Make published versions readable by everyone. Otherwise only staff and the parties may read them.",
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("legal_name", models.CharField(max_length=255, verbose_name="legal name")),
                ("jurisdiction", models.CharField(max_length=100, verbose_name="state or country of organization")),
                (
                    "entity_type",
                    models.CharField(
                        help_text="For example: corporation or limited liability company.", max_length=100
                    ),
                ),
                ("address", models.TextField(verbose_name="principal place of business")),
                ("covered_entities", models.TextField(help_text="One name per line.", verbose_name="covered entities")),
                ("discount", models.CharField(default="none", max_length=64)),
                ("authorized_contacts", models.JSONField(default=list)),
                ("billing_contact_name", models.CharField(max_length=255)),
                ("billing_contact_email", models.EmailField(max_length=254)),
                (
                    "notices_contact",
                    models.TextField(blank=True, help_text="Only if different from the principal place of business."),
                ),
                ("catalog_snapshot", models.JSONField(blank=True, default=dict, editable=False)),
                ("program_title_snapshot", models.CharField(blank=True, editable=False, max_length=255)),
                (
                    "agreement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order",
                        to="agreements.agreement",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="The python.org account that may view the order and sign it online.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agreement_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="orders", to="agreements.program"
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("agreement", models.SlugField(max_length=64)),
                ("tier", models.CharField(max_length=64)),
                ("addons", models.JSONField(blank=True, default=dict)),
                ("special_terms", models.TextField(blank=True, help_text="Set by staff only; leave empty for none.")),
                ("pricing", models.JSONField(blank=True, default=dict, editable=False)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="agreements", to="agreements.order"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("order", "agreement"), name="one_order_line_per_agreement")
                ],
            },
        ),
    ]
