# Generated by Django 5.2.13 on 2026-06-24 15:33

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nominations", "0002_auto_20190514_1435"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectionKind",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                (
                    "accent_color",
                    colorfield.fields.ColorField(
                        default="#0073b7",
                        help_text="Accent color used to theme this kind's pages.",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="election",
            name="kind",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="elections",
                to="nominations.electionkind",
            ),
        ),
    ]
