# Generated by Django 5.2.17 on 2026-10-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nominations", "0004_acknowledgments_and_form_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="endorsements_close_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="election",
            name="endorsements_open_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nomination",
            name="is_endorsement",
            field=models.BooleanField(
                default=False, help_text="Submitted via the endorsement window for an already-approved candidate."
            ),
        ),
    ]
