# Generated by Django 4.2.28 on 2026-02-06 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nominations', '0002_auto_20190514_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='FellowNominationRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('quarter', models.PositiveSmallIntegerField(choices=[(1, 'Q1 (Jan-Mar)'), (2, 'Q2 (Apr-Jun)'), (3, 'Q3 (Jul-Sep)'), (4, 'Q4 (Oct-Dec)')])),
                ('quarter_start', models.DateField(help_text='First day of the quarter.')),
                ('quarter_end', models.DateField(help_text='Last day of the quarter.')),
                ('nominations_cutoff', models.DateField(help_text='20th of month 2 per WG Charter (Feb 20, May 20, Aug 20, Nov 20).')),
                ('review_start', models.DateField(help_text='Same as nominations cutoff.')),
                ('review_end', models.DateField(help_text='20th of month 3 (Mar 20, Jun 20, Sep 20, Dec 20).')),
                ('is_open', models.BooleanField(default=True, help_text='Whether accepting nominations.')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['-year', '-quarter'],
                'unique_together': {('year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='FellowNomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('nominee_name', models.CharField(max_length=255)),
                ('nominee_email', models.EmailField(max_length=255)),
                ('nomination_statement', markupfield.fields.MarkupField(rendered_field=True)),
                ('nomination_statement_markup_type', models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown'), ('restructuredtext', 'Restructured Text')], default='markdown', editable=False, max_length=30)),
                ('_nomination_statement_rendered', models.TextField(editable=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('not_accepted', 'Not Accepted')], db_index=True, default='pending', max_length=20)),
                ('nominee_is_fellow_at_submission', models.BooleanField(default=False, help_text='Snapshot: was the nominee already a Fellow at submission time?')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL)),
                ('expiry_round', models.ForeignKey(blank=True, help_text='Round 4 quarters after submission; nomination expires after this round.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expiring_nominations', to='nominations.fellownominationround')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('nomination_round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominations', to='nominations.fellownominationround')),
                ('nominator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fellow_nominations_made', to=settings.AUTH_USER_MODEL)),
                ('nominee_user', models.ForeignKey(blank=True, help_text='Linked if nominee has a python.org account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fellow_nominations_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='FellowNominationVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('abstain', 'Abstain')], max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='nominations.fellownomination')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fellow_nomination_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('nomination', 'voter')},
            },
        ),
    ]
