name: "Bug Report"
description: Report a bug with python.org website to help us improve
title: "Bug: <title>"
labels: ["bug", "Triage Required"]

body:
  - type: markdown
    attributes:
      value: |
        This is the repository and issue tracker for the https://www.python.org website.

        If you're looking to file an issue with CPython itself, please click here: [CPython Issues](https://github.com/python/cpython/issues/new/choose).

        Issues related to [Python's documentation](https://docs.python.org) can also be filed [here](https://github.com/python/cpython/issues/new?assignees=&labels=docs&template=documentation.md).

  - type: textarea
    id: description
    attributes:
      label: "Describe the bug"
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: "To Reproduce"
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: input
    id: reprod-url
    attributes:
      label: "URL to the issue"
      description: Please enter the URL to provide a reproduction of the issue, if applicable
      placeholder: ex. https://python.org/my-issue/here
    validations:
      required: false

  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      value: |
        "![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
      render: bash
    validations:
      required: false

  - type: dropdown
    id: browsers
    attributes:
      label: "Browsers"
      description: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: "Operating System"
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
        - iOS
        - Android
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: "Browser Version"
      description: What version of the browser are you using?
      placeholder: "e.g. 22"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: "Relevant log output"
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: "Additional context"
      description: Add any other context about the problem here.
    validations:
      required: false
