name: "Documentation Update"
description: Create an issue for documentation changes
title: "Docs: <title>"
labels: ["documentation"]

body:
  - type: markdown
    attributes:
      value: |
        This is the repository and issue tracker for the https://www.python.org website.

        If you're looking to file an issue with CPython itself, please click here: [CPython Issues](https://github.com/python/cpython/issues/new/choose).

        Issues related to [Python's documentation](https://docs.python.org) can also be filed [here](https://github.com/python/cpython/issues/new?assignees=&labels=docs&template=documentation.md).

  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief summary of your request
      placeholder: We need to update the documentation to include information about...
    validations:
      required: true
