# Generated by Django 2.0.6 on 2018-09-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='last_modified_by',
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
        migrations.DeleteModel(
            name='Translation',
        ),
    ]
