# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-31 05:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20170831_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
