# Generated by Django 2.0.13 on 2020-10-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0006_auto_20201016_1517"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsorshipbenefit",
            name="packages",
            field=models.ManyToManyField(
                blank=True,
                help_text="What sponsorship packages this benefit is included in.",
                related_name="benefits",
                to="sponsors.SponsorshipPackage",
                verbose_name="Sponsorship Packages",
            ),
        ),
    ]
