# Generated by Django 2.0.13 on 2021-02-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0018_auto_20201201_1659"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="twitter_handle",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="Sponsor twitter hanlde",
            ),
        ),
    ]
