# Generated by Django 2.0.13 on 2020-12-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0020_auto_20201210_1802"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statementofwork",
            name="document",
            field=models.FileField(
                blank=True,
                upload_to="sponsors/statmentes_of_work/",
                verbose_name="Unsigned PDF",
            ),
        ),
        migrations.AlterField(
            model_name="statementofwork",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("outdated", "Outdated"),
                    ("awaiting signature", "Awaiting signature"),
                    ("executed", "Executed"),
                    ("nullified", "Nullified"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
    ]
