# Generated by Django 2.0.13 on 2021-01-05 12:06

from django.db import migrations, models
import django.db.models.deletion
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("sponsors", "0022_sponsorcontact_administrative"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("outdated", "Outdated"),
                            ("awaiting signature", "Awaiting signature"),
                            ("executed", "Executed"),
                            ("nullified", "Nullified"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "revision",
                    models.PositiveIntegerField(default=0, verbose_name="Revision nº"),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        upload_to="sponsors/contracts/",
                        verbose_name="Unsigned PDF",
                    ),
                ),
                (
                    "signed_document",
                    models.FileField(
                        blank=True,
                        upload_to="sponsors/contracts/signed/",
                        verbose_name="Signed PDF",
                    ),
                ),
                ("sponsor_info", models.TextField(verbose_name="Sponsor information")),
                ("sponsor_contact", models.TextField(verbose_name="Sponsor contact")),
                ("benefits_list", markupfield.fields.MarkupField(rendered_field=True)),
                (
                    "benefits_list_markup_type",
                    models.CharField(
                        choices=[
                            ("", "--"),
                            ("html", "HTML"),
                            ("plain", "Plain"),
                            ("markdown", "Markdown"),
                            ("restructuredtext", "Restructured Text"),
                        ],
                        default="markdown",
                        editable=False,
                        max_length=30,
                    ),
                ),
                ("legal_clauses", markupfield.fields.MarkupField(rendered_field=True)),
                ("_benefits_list_rendered", models.TextField(editable=False)),
                (
                    "legal_clauses_markup_type",
                    models.CharField(
                        choices=[
                            ("", "--"),
                            ("html", "HTML"),
                            ("plain", "Plain"),
                            ("markdown", "Markdown"),
                            ("restructuredtext", "Restructured Text"),
                        ],
                        default="markdown",
                        editable=False,
                        max_length=30,
                    ),
                ),
                ("created_on", models.DateField(auto_now_add=True)),
                ("_legal_clauses_rendered", models.TextField(editable=False)),
                ("last_update", models.DateField(auto_now=True)),
                ("sent_on", models.DateField(null=True)),
                (
                    "sponsorship",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract",
                        to="sponsors.Sponsorship",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
            },
        ),
        migrations.RemoveField(
            model_name="statementofwork",
            name="sponsorship",
        ),
        migrations.AlterField(
            model_name="legalclause",
            name="clause",
            field=models.TextField(
                help_text="Legal clause text to be added to contract",
                verbose_name="Clause",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorbenefit",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="For display in the contract and sponsor dashboard.",
                null=True,
                verbose_name="Benefit Description",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorbenefit",
            name="name",
            field=models.CharField(
                help_text="For display in the contract and sponsor dashboard.",
                max_length=1024,
                verbose_name="Benefit Name",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipbenefit",
            name="legal_clauses",
            field=models.ManyToManyField(
                blank=True,
                help_text="Legal clauses to be displayed in the contract",
                related_name="benefits",
                to="sponsors.LegalClause",
                verbose_name="Legal Clauses",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipbenefit",
            name="name",
            field=models.CharField(
                help_text="For display in the application form, contract, and sponsor dashboard.",
                max_length=1024,
                verbose_name="Benefit Name",
            ),
        ),
        migrations.DeleteModel(
            name="StatementOfWork",
        ),
    ]
