# Generated by Django 2.0.13 on 2021-04-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0023_merge_20210406_1522'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatementOfWork',
            new_name='Contract',
        ),
    ]
