# Generated by Django 2.0.13 on 2021-04-14 15:41

from django.db import migrations


def create_contracts(apps, schema_editor):
    Contract = apps.get_model('sponsors', 'Contract')
    Sponsorship = apps.get_model('sponsors', 'Sponsorship')

    for sponsorship in Sponsorship.objects.filter(status='approved'):
        if not sponsorship.contract:
            Contract.new(sponsorship)


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0024_auto_20210414_1449'),
    ]

    operations = [
        migrations.RunPython(create_contracts, migrations.RunPython.noop)
    ]
