# Generated by Django 2.0.13 on 2021-09-08 13:57

from django.db import migrations


def update_package_as_advertisable(apps, schema_editor):
    SponsorshipPackage = apps.get_model("sponsors.SponsorshipPackage")
    # initial sponsorship packages should remaing visible in the form
    SponsorshipPackage.objects.all().update(advertise=True)


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0046_sponsorshippackage_advertise'),
    ]

    operations = [
        migrations.RunPython(update_package_as_advertisable, migrations.RunPython.noop)
    ]
