# Generated by Django 2.2.24 on 2021-09-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0047_auto_20210908_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorshippackage',
            name='advertise',
            field=models.BooleanField(blank=True, default=False, help_text='If checked, this package will be advertised in the sponsosrhip application'),
        ),
    ]
