# Generated by Django 2.2.24 on 2021-10-22 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0050_emailtargetable_emailtargetableconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='description',
            field=models.TextField(help_text='Brief description of the sponsor for public display.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='landing_page_url',
            field=models.URLField(blank=True, help_text='Landing page URL. This may be provided by the sponsor, however the linked page may not contain any sales or marketing information.', null=True, verbose_name='Landing page URL'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(help_text='Name of the sponsor, for public display.', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='primary_phone',
            field=models.CharField(max_length=32, verbose_name='Primary Phone'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='print_logo',
            field=models.FileField(blank=True, help_text='For printed materials, signage, and projection. SVG or EPS', null=True, upload_to='sponsor_print_logos', verbose_name='Print logo'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Twitter handle'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='web_logo',
            field=models.ImageField(help_text='For display on our sponsor webpage. High resolution PNG or JPG, smallest dimension no less than 256px', upload_to='sponsor_web_logos', verbose_name='Web logo'),
        ),
        migrations.AlterField(
            model_name='sponsorcontact',
            name='primary',
            field=models.BooleanField(default=False, help_text='The primary contact for a sponsorship will be responsible for managing deliverables we need to fulfill benefits. Primary contacts will receive all email notifications regarding sponsorship. '),
        ),
    ]
