# Generated by Django 2.2.24 on 2021-10-22 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0051_auto_20211022_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredImgAsset',
            fields=[
                ('benefitfeature_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sponsors.BenefitFeature')),
                ('related_to', models.CharField(choices=[('sponsor', 'Sponsor'), ('sponsorship', 'Sponsorship')], help_text='To which instance (Sponsor or Sponsorship) should this asset relate to.', max_length=30, verbose_name='Related To')),
                ('internal_name', models.CharField(db_index=True, help_text='Unique name used internally to control if the sponsor/sponsorship already has the asset', max_length=128, unique=True, verbose_name='Internal Name')),
                ('min_width', models.PositiveIntegerField()),
                ('max_width', models.PositiveIntegerField()),
                ('min_height', models.PositiveIntegerField()),
                ('max_height', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Require Image Benefit',
                'verbose_name_plural': 'Require Image Benefits',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sponsors.benefitfeature', models.Model),
        ),
        migrations.CreateModel(
            name='RequiredImgAssetConfiguration',
            fields=[
                ('benefitfeatureconfiguration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sponsors.BenefitFeatureConfiguration')),
                ('related_to', models.CharField(choices=[('sponsor', 'Sponsor'), ('sponsorship', 'Sponsorship')], help_text='To which instance (Sponsor or Sponsorship) should this asset relate to.', max_length=30, verbose_name='Related To')),
                ('internal_name', models.CharField(db_index=True, help_text='Unique name used internally to control if the sponsor/sponsorship already has the asset', max_length=128, unique=True, verbose_name='Internal Name')),
                ('min_width', models.PositiveIntegerField()),
                ('max_width', models.PositiveIntegerField()),
                ('min_height', models.PositiveIntegerField()),
                ('max_height', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Require Image Configuration',
                'verbose_name_plural': 'Require Image Configurations',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sponsors.benefitfeatureconfiguration', models.Model),
        ),
    ]
