# Generated by Django 2.2.24 on 2021-10-26 14:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0053_genericasset_imgasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericasset',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, serialize=False),
        ),
    ]
