# Generated by Django 2.2.24 on 2021-10-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0058_auto_20211029_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textasset',
            options={'verbose_name': 'Text Asset', 'verbose_name_plural': 'Text Assets'},
        ),
    ]
