# Generated by Django 2.2.24 on 2021-11-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0059_auto_20211029_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='logoplacement',
            name='describe_as_sponsor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logoplacement',
            name='link_to_sponsors_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logoplacementconfiguration',
            name='describe_as_sponsor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logoplacementconfiguration',
            name='link_to_sponsors_page',
            field=models.BooleanField(default=False),
        ),
    ]
