# Generated by Django 2.2.24 on 2022-01-11 20:55

from django.db import migrations, models
import django.db.models.deletion
import sponsors.models.assets
import sponsors.models.benefits


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0069_auto_20220110_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('genericasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sponsors.GenericAsset')),
                ('file', models.FileField(null=True, upload_to=sponsors.models.assets.generic_asset_path)),
            ],
            options={
                'verbose_name': 'File Asset',
                'verbose_name_plural': 'File Assets',
            },
            bases=('sponsors.genericasset',),
        ),
        migrations.CreateModel(
            name='ProvidedFileAsset',
            fields=[
                ('benefitfeature_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sponsors.BenefitFeature')),
                ('related_to', models.CharField(choices=[('sponsor', 'Sponsor'), ('sponsorship', 'Sponsorship')], help_text='To which instance (Sponsor or Sponsorship) should this asset relate to.', max_length=30, verbose_name='Related To')),
                ('internal_name', models.CharField(db_index=True, help_text='Unique name used internally to control if the sponsor/sponsorship already has the asset', max_length=128, verbose_name='Internal Name')),
                ('shared', models.BooleanField(default=False)),
                ('label', models.CharField(help_text="What's the title used to display the file to the sponsor?", max_length=256)),
                ('help_text', models.CharField(blank=True, default='', help_text='Any helper comment on how the file should be used', max_length=256)),
                ('shared_file', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Provided File',
                'verbose_name_plural': 'Provided Files',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(sponsors.models.benefits.ProvidedAssetMixin, 'sponsors.benefitfeature', models.Model),
        ),
        migrations.CreateModel(
            name='ProvidedFileAssetConfiguration',
            fields=[
                ('benefitfeatureconfiguration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sponsors.BenefitFeatureConfiguration')),
                ('related_to', models.CharField(choices=[('sponsor', 'Sponsor'), ('sponsorship', 'Sponsorship')], help_text='To which instance (Sponsor or Sponsorship) should this asset relate to.', max_length=30, verbose_name='Related To')),
                ('internal_name', models.CharField(db_index=True, help_text='Unique name used internally to control if the sponsor/sponsorship already has the asset', max_length=128, verbose_name='Internal Name')),
                ('shared', models.BooleanField(default=False)),
                ('label', models.CharField(help_text="What's the title used to display the file to the sponsor?", max_length=256)),
                ('help_text', models.CharField(blank=True, default='', help_text='Any helper comment on how the file should be used', max_length=256)),
                ('shared_file', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Provided File Configuration',
                'verbose_name_plural': 'Provided File Configurations',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(sponsors.models.benefits.AssetConfigurationMixin, 'sponsors.benefitfeatureconfiguration', models.Model),
        ),
        migrations.AddField(
            model_name='providedtextasset',
            name='shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providedtextassetconfiguration',
            name='shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='providedfileassetconfiguration',
            constraint=models.UniqueConstraint(fields=('internal_name',), name='uniq_provided_file_asset_cfg'),
        ),
    ]
