# Generated by Django 2.2.24 on 2022-07-28 15:50

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0075_auto_20220303_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefitfeature',
            options={'base_manager_name': 'non_polymorphic', 'verbose_name': 'Benefit Feature', 'verbose_name_plural': 'Benefit Features'},
        ),
        migrations.AlterModelOptions(
            name='genericasset',
            options={'base_manager_name': 'non_polymorphic', 'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
        migrations.AlterModelManagers(
            name='benefitfeature',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='fileasset',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='genericasset',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='imgasset',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='responseasset',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='textasset',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
    ]
