# Generated by Django 2.2.24 on 2022-07-29 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0081_sponsorship_application_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsorship',
            old_name='application_year',
            new_name='year',
        ),
    ]
