# Generated by Django 2.2.24 on 2022-08-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0090_auto_20220812_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshippackage',
            name='allow_a_la_carte',
            field=models.BooleanField(default=True, help_text='If disabled, a la carte benefits will be disabled in application form'),
        ),
    ]
