# Generated by Django 2.2.24 on 2023-12-14 20:25

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sponsors", "0094_sponsorship_locked"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="benefitfeatureconfiguration",
            options={
                "base_manager_name": "non_polymorphic",
                "verbose_name": "Benefit Feature Configuration",
                "verbose_name_plural": "Benefit Feature Configurations",
            },
        ),
        migrations.AlterModelManagers(
            name="benefitfeatureconfiguration",
            managers=[
                ("non_polymorphic", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="emailtargetableconfiguration",
            managers=[
                ("non_polymorphic", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="logoplacementconfiguration",
            managers=[
                ("non_polymorphic", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="providedfileassetconfiguration",
            managers=[
                ("non_polymorphic", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="providedtextassetconfiguration",
            managers=[
                ("non_polymorphic", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="requiredimgassetconfiguration",
            managers=[
                ("non_polymorphic", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="requiredresponseassetconfiguration",
            managers=[
                ("non_polymorphic", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="requiredtextassetconfiguration",
            managers=[
                ("non_polymorphic", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="tieredbenefitconfiguration",
            managers=[
                ("non_polymorphic", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
