# Generated by Django 2.2.24 on 2023-12-14 21:08

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0095_auto_20231214_2025'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='benefitfeatureconfiguration',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='emailtargetableconfiguration',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='logoplacementconfiguration',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='providedfileassetconfiguration',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='providedtextassetconfiguration',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='requiredimgassetconfiguration',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='requiredresponseassetconfiguration',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='requiredtextassetconfiguration',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='tieredbenefitconfiguration',
            managers=[
            ],
        ),
    ]
