# Generated by Django 2.2.24 on 2023-12-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0096_auto_20231214_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='renewal',
            field=models.BooleanField(default=False),
        ),
    ]
