# Generated by Django 2.2.28 on 2024-05-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0101_sponsor_linked_in_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textasset',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
