# Generated by Django 4.2.22 on 2025-06-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0103_alter_benefitfeature_polymorphic_ctype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='cancelled_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('finalized', 'Finalized'), ('cancelled', 'Cancelled')], db_index=True, default='applied', max_length=20),
        ),
    ]
