# Generated by Django 5.2.11 on 2026-02-25 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("downloads", "0014_releasefile_sha256_sum"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="releasefile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("url__exact", ""),
                        ("url__startswith", "https://www.python.org/"),
                        ("url__startswith", "http://www.python.org/"),
                        _connector="OR",
                    ),
                    models.Q(
                        ("gpg_signature_file__exact", ""),
                        ("gpg_signature_file__startswith", "https://www.python.org/"),
                        ("gpg_signature_file__startswith", "http://www.python.org/"),
                        _connector="OR",
                    ),
                    models.Q(
                        ("sigstore_signature_file__exact", ""),
                        ("sigstore_signature_file__startswith", "https://www.python.org/"),
                        ("sigstore_signature_file__startswith", "http://www.python.org/"),
                        _connector="OR",
                    ),
                    models.Q(
                        ("sigstore_cert_file__exact", ""),
                        ("sigstore_cert_file__startswith", "https://www.python.org/"),
                        ("sigstore_cert_file__startswith", "http://www.python.org/"),
                        _connector="OR",
                    ),
                    models.Q(
                        ("sigstore_bundle_file__exact", ""),
                        ("sigstore_bundle_file__startswith", "https://www.python.org/"),
                        ("sigstore_bundle_file__startswith", "http://www.python.org/"),
                        _connector="OR",
                    ),
                    models.Q(
                        ("sbom_spdx2_file__exact", ""),
                        ("sbom_spdx2_file__startswith", "https://www.python.org/"),
                        ("sbom_spdx2_file__startswith", "http://www.python.org/"),
                        _connector="OR",
                    ),
                ),
                name="only_python_dot_org_urls",
                violation_error_message="All file URLs must begin with 'https://www.python.org/'",
            ),
        ),
    ]
