# Generated by Django 4.2.20 on 2025-04-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0011_alter_os_creator_alter_os_last_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='version',
            field=models.IntegerField(choices=[(3, 'Python 3.x.x'), (2, 'Python 2.x.x'), (1, 'Python 1.x.x'), (100, 'Python install manager')], default=3),
        ),
    ]
