# Generated by Django 5.2.11 on 2026-02-22 08:34

from django.db import migrations


def rewrite_blog_urls(apps, schema_editor):
    BlogEntry = apps.get_model("blogs", "BlogEntry")
    entries_to_update = []
    for entry in BlogEntry.objects.filter(url__contains="pythoninsider.blogspot.com"):
        entry.url = entry.url.replace("pythoninsider.blogspot.com", "blog.python.org")
        entries_to_update.append(entry)
    if entries_to_update:
        BlogEntry.objects.bulk_update(entries_to_update, ['url'])


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_relatedblog_creator_and_more'),
    ]

    operations = [
        migrations.RunPython(rewrite_blog_urls, migrations.RunPython.noop),
    ]
