# Generated by Django 5.2.11 on 2026-04-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sponsors", "0103_alter_benefitfeature_polymorphic_ctype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="white_logo",
            field=models.ImageField(
                blank=True,
                help_text="For display on dark backgrounds (e.g. PyPI footer). Transparent PNG, smallest dimension no less than 256px",
                null=True,
                upload_to="sponsor_white_logos",
                verbose_name="White logo",
            ),
        ),
    ]
