# Generated by Django 5.2.11 on 2026-03-22 20:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sponsors", "0103_alter_benefitfeature_polymorphic_ctype_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SponsorshipNotificationLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(max_length=500)),
                ("content", models.TextField(blank=True)),
                ("recipients", models.TextField(help_text="Comma-separated email addresses")),
                ("contact_types", models.CharField(blank=True, max_length=200)),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "sponsorship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to="sponsors.sponsorship",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Log",
                "verbose_name_plural": "Notification Logs",
                "ordering": ["-sent_at"],
            },
        ),
    ]
