# Generated by Django 5.2.16 on 2026-09-19 19:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sponsors", "0104_add_sponsor_white_logo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailtargetable",
            options={"verbose_name": "Email Targetable Benefit", "verbose_name_plural": "Email Targetable Benefits"},
        ),
        migrations.AlterModelOptions(
            name="emailtargetableconfiguration",
            options={
                "verbose_name": "Email Targetable Configuration",
                "verbose_name_plural": "Email Targetable Configurations",
            },
        ),
        migrations.AlterModelOptions(
            name="logoplacement",
            options={"verbose_name": "Logo Placement", "verbose_name_plural": "Logo Placement"},
        ),
        migrations.AlterModelOptions(
            name="logoplacementconfiguration",
            options={
                "verbose_name": "Logo Placement Configuration",
                "verbose_name_plural": "Logo Placement Configurations",
            },
        ),
        migrations.AlterModelOptions(
            name="providedfileasset",
            options={"verbose_name": "Provided File", "verbose_name_plural": "Provided Files"},
        ),
        migrations.AlterModelOptions(
            name="providedfileassetconfiguration",
            options={
                "verbose_name": "Provided File Configuration",
                "verbose_name_plural": "Provided File Configurations",
            },
        ),
        migrations.AlterModelOptions(
            name="providedtextasset",
            options={"verbose_name": "Provided Text", "verbose_name_plural": "Provided Texts"},
        ),
        migrations.AlterModelOptions(
            name="providedtextassetconfiguration",
            options={
                "verbose_name": "Provided Text Configuration",
                "verbose_name_plural": "Provided Text Configurations",
            },
        ),
        migrations.AlterModelOptions(
            name="requiredimgasset",
            options={"verbose_name": "Require Image", "verbose_name_plural": "Require Images"},
        ),
        migrations.AlterModelOptions(
            name="requiredimgassetconfiguration",
            options={
                "verbose_name": "Require Image Configuration",
                "verbose_name_plural": "Require Image Configurations",
            },
        ),
        migrations.AlterModelOptions(
            name="requiredresponseasset",
            options={"verbose_name": "Require Response", "verbose_name_plural": "Required Responses"},
        ),
        migrations.AlterModelOptions(
            name="requiredresponseassetconfiguration",
            options={
                "verbose_name": "Require Response Configuration",
                "verbose_name_plural": "Require Response Configurations",
            },
        ),
        migrations.AlterModelOptions(
            name="requiredtextasset",
            options={"verbose_name": "Require Text", "verbose_name_plural": "Require Texts"},
        ),
        migrations.AlterModelOptions(
            name="requiredtextassetconfiguration",
            options={
                "verbose_name": "Require Text Configuration",
                "verbose_name_plural": "Require Text Configurations",
            },
        ),
        migrations.AlterModelOptions(
            name="tieredbenefit",
            options={"verbose_name": "Tiered Benefit", "verbose_name_plural": "Tiered Benefits"},
        ),
        migrations.AlterModelOptions(
            name="tieredbenefitconfiguration",
            options={
                "verbose_name": "Tiered Benefit Configuration",
                "verbose_name_plural": "Tiered Benefit Configurations",
            },
        ),
    ]
