# Generated by Django 5.2.16 on 2026-09-22 03:35

import django.db.models.deletion
from django.db import migrations, models

import apps.sponsors.models.contract
import apps.sponsors.storage


def backfill_original_sponsorship(apps, schema_editor):
    """Leave detached contracts unassigned; names cannot establish ownership."""
    Contract = apps.get_model("sponsors", "Contract")
    Contract.objects.filter(sponsorship__isnull=False, original_sponsorship__isnull=True).update(
        original_sponsorship=models.F("sponsorship")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("sponsors", "0105_add_notification_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="original_sponsorship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contract_history",
                to="sponsors.sponsorship",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="document",
            field=models.FileField(
                blank=True,
                storage=apps.sponsors.storage.get_contract_storage,
                upload_to="sponsors/contracts/",
                verbose_name="Unsigned PDF",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="document_docx",
            field=models.FileField(
                blank=True,
                storage=apps.sponsors.storage.get_contract_storage,
                upload_to="sponsors/contracts/docx/",
                verbose_name="Unsigned Docx",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="signed_document",
            field=models.FileField(
                blank=True,
                storage=apps.sponsors.storage.get_contract_storage,
                upload_to=apps.sponsors.models.contract.signed_contract_random_path,
                verbose_name="Signed PDF",
            ),
        ),
        migrations.RunPython(backfill_original_sponsorship, migrations.RunPython.noop),
    ]
