# Generated by Django 5.2.17 on 2026-10-06 23:11

from django.db import migrations, models

import apps.sponsors.storage


class Migration(migrations.Migration):
    dependencies = [
        ("sponsors", "0107_contract_private_storage_and_original_sponsorship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="document",
            field=models.FileField(
                blank=True,
                max_length=255,
                storage=apps.sponsors.storage.get_contract_storage,
                upload_to="sponsors/contracts/",
                verbose_name="Unsigned PDF",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="document_docx",
            field=models.FileField(
                blank=True,
                max_length=255,
                storage=apps.sponsors.storage.get_contract_storage,
                upload_to="sponsors/contracts/docx/",
                verbose_name="Unsigned Docx",
            ),
        ),
    ]
