# Generated by Django 2.0.6 on 2018-07-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_change_end_date_for_occurring_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
