name: Check collectstatic

on: [push, pull_request, workflow_dispatch]

permissions: {}

jobs:
  collectstatic:
    if: github.event_name != 'push' || github.event.repository.fork == true || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
            python-version-file: '.python-version'
      - name: Cache Python dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        env:
          cache-name: pythondotorg-cache-pip
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-
            ${{ runner.os }}-${{ github.job }}-
            ${{ runner.os }}-
      - name: Install Python dependencies
        run: |
          pip install -U pip setuptools wheel
          pip install '.[prod]'
      - name: Run Tests
        run: |
          DJANGO_SETTINGS_MODULE=pydotorg.settings.static python manage.py collectstatic --noinput
