name: Check collectstatic

on: [push, pull_request, workflow_dispatch]

permissions: {}

jobs:
  collectstatic:
    if: github.event_name != 'push' || github.event.repository.fork == true || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
            python-version-file: '.python-version'
      - name: Cache Python dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        env:
          cache-name: pythondotorg-cache-pip
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-
            ${{ runner.os }}-${{ github.job }}-
            ${{ runner.os }}-
      - name: Install Python dependencies
        run: |
          pip install -U pip setuptools wheel
          pip install '.[prod]'
      - name: Run Tests
        run: |
          DJANGO_SETTINGS_MODULE=pydotorg.settings.static python manage.py collectstatic --noinput
